name: speakers_list
description: "A simple Flutter app for managing a list of speakers."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.0
  clock: ^1.1.1
  collection: ^1.18.0
  fake_async: ^1.3.2
  intl: ^0.17.0
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  path: ^1.9.0
  provider: ^6.1.2
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.4
  vm_service: ^14.2.5

dev_dependencies:
  flutter_lints: ^5.0.0
  #lints: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/languages/de.json
    - assets/languages/en.json
    - assets/languages/fr.json